# Generated by Django 2.1.1 on 2018-11-20 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_inscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='matiere',
        ),
        migrations.AddField(
            model_name='eleve',
            name='matieres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Maths', max_length=30), default=['Maths'], size=10),
            preserve_default=False,
        ),
    ]
