# Generated by Django 2.1.1 on 2018-11-20 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_inscription', '0002_auto_20181120_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matieres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=10),
        ),
    ]
